### ISSUE TITLE
EDA plot 1

### ISSUE THREAD

**Issue by shusterc** [UBC-MDS/DSCI_522_Salary-vs-College#10]
Hi guys:

Great progress on the EDA plots, I have some suggestion on how we can improve them:
1. plot 1: salary by degree
- using plotly is nice but I think this is too much data for EDA
- the plot doesn't visualize the relationship between our variables of interest easily: degree and salary
- it is intuitive that salary increases as the percentile is increased, within each degree....
- IMPROVEMENT: 
    - plot degree on y-axis, salary on x-axis, use geom_point
    - facet by salary i.e. create a plot for each salary type: starting salary, mid-career salary, etc

**Comment by pak-alex** [comment]
Due to its complexity, we decided to move away from `plotly` and use `ggplot`. Plotly files on the repo will be deleted. New EDA visualizations for our data will be made. See #18.
