### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_Salary-vs-College#13]
__Mechanics__

* The link in your proposal repo only redirect to the release page of the project repo. You can also create a direct link to v1.0 of the repo with https://github.com/UBC-MDS/DSCI_522_Salary-vs-College/tree/v1.0.

* In README, could have changed the title from he default repo name to a project name, e.g. ‘Salary vs College’ or something more informative.

* Would be nice to have a snapshot of the imported data in README, say, showing the first few rows with column titles, just to let the reader get a better feel of what is available in the data set.

**Comment by shusterc** [comment]
Alex added links to the version in the README, he also added snapshots of the imported .csv files

**Comment by pak-alex** [comment]
See 48ceaae3cc0b797b9f0fbb51def6932f26686160 for fix.
