### ISSUE TITLE
Potential Visualizations for EDA 

### ISSUE THREAD

**Issue by pak-alex** [UBC-MDS/DSCI_522_Salary-vs-College#18]
Some potential plots that we may be able to visualize: 

For the Degree vs Salary .csv, we can create dumbbell plots: 
* From starting median salary to mid-career median salary, arranged by starting median salary
* From starting median salary to mid-career median salary, arranged by mid-career salary
* From 10'th to 90'th percentile mid-career median salary, with a point at the 50'th percentile median, arranged by the 50'th percentile median

For the Type/Region vs Salary .csv, we can create the following plots: 
* Bar plot comparing region vs. salary, facet by 10'th, 50'th, 90'th percentiles
* Bar plot comparing type vs. salary, facet by 10'th, 50'th, 90'th percentiles 
* Dumbbell plot comparing region vs. salary, starting median salary to mid median salary, showing the range
* Dumbbell plot comparing type vs. salary, starting median salary to mid median salary, showing the range

From here, we will be able to visualize any relationships in the data.

**Comment by shusterc** [comment]
I agree lets start with these plots and see what hypothesis we can generate from this 👍
