### ISSUE TITLE
Re-organize the results folder?

### ISSUE THREAD

**Issue by lyyu0413** [UBC-MDS/DSCI_522_Salary-vs-College#22]
After we finished the EDA, should we re-structure our results folder since there are so many plot? Many be put figures created by the same script in the same folder under the folder name EDA?
e.g. .../results/EDA/NAME-OF-THE-SCRIPT/figures?

**Comment by shusterc** [comment]
I agree, I think we should create:
- EDA folder
- ANOVA folder
- Tukey tests
