### ISSUE TITLE
Peer Review Feedback (Alex Hope, Sabrina Tse) 

### ISSUE THREAD

**Issue by pak-alex** [UBC-MDS/DSCI_522_Salary-vs-College#33]
Two major points about our final report: 

* Data tables in the final report are overwhelming; would be much better to find some way to shorten them or only show the relevant points 

* Could make our findings more meaningful by relating the ANOVA/Tukey results back towards our initial findings in the EDA (ex. Was everything as we expected? Or were there results we thought we would find in the EDA that did not show up after hypothesis testing?)

**Comment by lyyu0413** [comment]
1. I think maybe we can filter out those rows that we are interested in, and add a hyperlink to the entire table in the final report?
2. We probably need to rephrase our sentences in the final report?
