### ISSUE TITLE
Peer Review Feedback (RIchie Zitomer, Jim Pushor)

### ISSUE THREAD

**Issue by shusterc** [UBC-MDS/DSCI_522_Salary-vs-College#35]
Below are the comments from the peer review session:

1.  Increase the reference section, look for references that did similar research and compare findings to theirs
2.  The table with the Tukey post-hoc tests should be minimized - one potential way to represent is by a matrix table showing which comparisons were significant
3.  In results consider telling a story for some of the variables, for example, how did salary by school region or type change over time.
4. Change the color scheme of the Bar graphs, increase title font for the bar graph

Let's start working on these!

**Comment by lyyu0413** [comment]
1. I think we have the reference, but we could expand the section for sure;
2.3. same as I addressed in Alex's feedback;
4. Working on that.
