### ISSUE TITLE
remove unhelpful info

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Salary-vs-College#45]
This section of your README (pasted below) could be deleted. It's not that useful to separately list the scripts, inputs and outputs. And they are listed (including their relationships to eachother in the Makefile.

---

To reproduce this project manually, run the scripts in this order:

src/Data_cleaning.R
src/Join_region_and_type.R
src/EDA_degree-vs-salary.R
src/EDA_region_and_school_type_to_salary
src/anova_tukey_tests.R
src/Increase_in_salary.R
src/Linear_Regression.R
Expected inputs:

data/raw_data/degrees-that-pay-back.csv
data/raw_data/salaries-by-college-type.csv
data/raw_data/salaries-by-region.csv
Expected outputs:

data/clean_data/clean_salary_by_degree.csv
data/clean_data/clean_salary_by_type.csv
data/clean_data/clean_salary_by_region.csv
results/degree_vs_mid_salary_range.png
results/degree_vs_salary_by_mid.png
results/degree_vs_salary_by_start.png
data/clean_data/clean_salary_by_region_type_join.csv
results/salary_change_Region.png
results/salary_change_SchoolType.png
results/salary_distribution_Region.png
results/salary_distribution_SchoolType.png
results/increase_in_salary.csv
results/anova_test/
results/lm_tests/
doc/college_salary_report.md

**Comment by shusterc** [comment]
removed, thanks.
