### ISSUE TITLE
missing dependencies for this rule

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Salary-vs-College#46]
https://github.com/UBC-MDS/DSCI_522_Salary-vs-College/blob/e835d7666c853c8e8aaa780863d4719f41f1677c/Makefile#L42

This rule (which builds the report as the target) depends on ALOT of files that are not listed here (i.e., all the images and csvs that you load in your report). These should all be listed as the dependencies (after `doc/Final_Report : doc/college_salary_report.Rmd`) in this rule.

**Comment by ttimbers** [comment]
A related comment is that your `all` dependency should really be `doc/college_salary_report.md`.

**Comment by shusterc** [comment]
I add all the dependencies to this rule and `all` dependency was changed to include only .md file
