### ISSUE TITLE
files not folders should be listed as targets

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Salary-vs-College#47]
https://github.com/UBC-MDS/DSCI_522_Salary-vs-College/blob/e835d7666c853c8e8aaa780863d4719f41f1677c/Makefile#L30

Files not folders should be listed as targets. Instead of `results/anova_results` as the target, all the files that this rule makes should be the target (no need to change the python script, just the Makefile rule). Same goes for this rule: `results/lm_tests : data/clean_data/clean_salary_by_region_type_join.csv src/Linear_Regression.R`

**Comment by lyyu0413** [comment]
We have changed the rules for the anova results and re-run the make all command in the docker container.

**Comment by pak-alex** [comment]
Fixed by @lyyu0413 as per d6e6fae35a49d1f2f277d37aeddf9c444b3523ff.
