### ISSUE TITLE
Importing data as numeric values

### ISSUE THREAD

**Issue by pak-alex** [UBC-MDS/DSCI_522_Salary-vs-College#5]
Currently, importing data from the csv files leaves the salary column as a character data type instead of a numeric data type. Moving forward, it would be easier to work with actual numbers rather than strings.

**Comment by lyyu0413** [comment]
I tried the gsub, it worked but we probably need to modify the code. I create the clean data anyway. Should we put the raw and cleaned data in separate folder and show the change on the directory structure?

**Comment by pak-alex** [comment]
@lyyu0413 nicely fixed the issue by creating a cleaning script. 

I don't think we need to put the raw and cleaned data in separate folders if we are clear with our file naming scheme. Let me know if you disagree though!
