### ISSUE TITLE
Data folder structure

### ISSUE THREAD

**Issue by shusterc** [UBC-MDS/DSCI_522_Salary-vs-College#9]
hi guys:

There is a few .csv files in this folder, I recommend we create a 'raw_data' folder and a 'clean_data folder'.

Also I recommend we create only two clean data files, they should be in 'tidy' format:
1. 'clean_salary_by_degree'
2. 'clean_salary_by_region_type' - this dataframe should be the joined data of the region and type raw data

**Comment by pak-alex** [comment]
I agree with the raw_data and the clean_data folder, this will help us with organization in the future. 

Would it be better to have a raw_data and clean_data as subfolders within the "data" folder? Or would it be better to have them in the root of the project?

**Comment by shusterc** [comment]
Lets make them inside the data folder!

**Comment by shusterc** [comment]
Resolved, we all agree
